/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'ProcessGreeting': EventHandler<{ timestamp: string; appName: string; greetingPrefix: string; requestId: string }, never>
    'HelloAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; status: string; appName: string }>, { topic: 'process-greeting'; data: { timestamp: string; appName: string; greetingPrefix: string; requestId: string } }>
    'PersistForecastResult': EventHandler<{ requestId: string; forecastResult: { requestId: string; productId: string; generatedAt: string; forecastMethod: string; confidenceLevel: number; forecastPeriods: Array<{ date: string; forecastValue: number; confidenceInterval: { lower: number; upper: number } }>; forecastSummary: { averageForecast: number; minForecast: number; maxForecast: number; trend: number; movingAverage?: number; trendSlope?: number } } }, never>
    'LoadHistoricalFacts': EventHandler<{ requestId: string; productId?: string; timeRange?: string }, { topic: 'generate-forecast'; data: { requestId: string; historicalData: { productId: string; timeRange: string; dailySales: Array<{ date: string; value: number }>; inventorySnapshots: Array<{ date: string; value: number }>; loadedAt: string }; forecastParameters: { method: string; confidenceLevel: number } } }>
    'GenerateForecast': EventHandler<{ requestId: string; historicalData: { productId: string; timeRange: string; dailySales: Array<{ date: string; value: number }>; inventorySnapshots: Array<{ date: string; value: number }>; loadedAt: string }; forecastParameters: { method: string; confidenceLevel: number } }, { topic: 'persist-forecast-result'; data: { requestId: string; forecastResult: { requestId: string; productId: string; generatedAt: string; forecastMethod: string; confidenceLevel: number; forecastPeriods: Array<{ date: string; forecastValue: number; confidenceInterval: { lower: number; upper: number } }>; forecastSummary: { averageForecast: number; minForecast: number; maxForecast: number; trend: number; movingAverage?: number; trendSlope?: number } } } }>
    'ForecastAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; status: string; requestId: string; productId?: string; timeRange?: string }>, { topic: 'load-historical-facts'; data: { requestId: string; productId?: string; timeRange?: string } }>
  }
    
}